interface ILineas { 
    auxiliar:number;
    codigoCP: number;
    cuenta: number;
    debe:number;
    dv?: string;
    empresa?:number;
    feDoc:string;
    feVen:string;
    fecha?:string;
    fechaReg?:string;
    flujo:number;
    fuente?:number;
    glosa:string;
    haber:number;
    item:number;
    noDoc:number;
    noDocL?:number;
    norma?: number;
    nroRef?: string;
    numero?:number;
    obra:number;
    partida?:number;
    periodo?:number;
    pptc?:number;
    pptcAsig?:string;
    proyecto?:number;
    referencia?:number;
    rut2?:number;
    td:number;
    tipo?:string;
    usuario?:string;
    type?:string;
    action?:string;
    item_nombre?:string;
    cuenta_nombre?:string;
    obra_nombre?:string;
    auxiliar_nombre?:string;
    flujo_nombre?:string;
    cuentaObject?:any;
}