export const tipoComprobantes = [
    { value: "A", text: "A CENTRALIZACIÓN AJUSTES"},
    { value: "B", text: "B CENTRALIZACIÓN BANCOS"},
    { value: "C", text: "C CENTRALIZACIÓN COMPRAS"},
    { value: "G", text: "G CENTRALIZACIÓN VENTAS GUIAS DESPACHO"},
    { value: "H", text: "H COMPROBANTE DE HONORARIOS"},
    { value: "I", text: "I COMPROBANTE DE INGRESO "},
    { value: "J", text: "J COMPROBANTE DE RENDICIÓN FONDOS"},
    { value: "K", text: "K COMPROBANTE DE FONDO FIJO"},
    { value: "E", text: "E COMPROBANTE DE EGRESO"},
    { value: "F", text: "F COMPROBANTE DE CAJA"},
    { value: "T", text: "T COMPROBANTE DE TRASPASO"},
    { value: "Z", text: "Z CENTRALIZACIÓN COSTOS VENTAS"},
    { value: "O", text: "O CENTRALIZACIÓN COSTOS MATERIALES"},
    { value: "P", text: "P CENTRALIZACIÓN COSTO PRODUCCIÓN"},
    { value: "R", text: "R CENTRALIZACIÓN RECEPCIONES"},
    { value: "L", text: "L CENTRALIZACIÓN MERMA OPERATIVA"},
    { value: "M", text: "M CENTRALIZACIÓN MERMA INVENTARIO"},
    { value: "S", text: "S CENTRALIZACIÓN REMUNERACIONES"},
    { value: "V", text: "V CENTRALIZACIÓN VENTAS"},
    { value: "X", text: "X CENTRALIZACIÓN PAGO PROVEEDORES"},
]